name: Auto Tag and Release

on:
  push:
    paths-ignore:
      - .github/**
      - docs/**
      - examples/**
    branches:
      - main

jobs:
  tag-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Run tests
        run: go test ./...

      - name: Extract version from version.go
        id: extract_version
        run: |
          if [ -f version.go ]; then
            VERSION=$(grep -oP 'Version = "\K[^"]+' version.go)
            # Add 'v' prefix to version
            VERSION="v$VERSION"
            echo "VERSION=$VERSION" >> $GITHUB_ENV
            echo "Extracted version: $VERSION"
          else
            echo "version.go does not exist. Setting default version v0.0.1"
            echo "VERSION=v0.0.1" >> $GITHUB_ENV
            echo "VERSION_FILE_EXISTS=false" >> $GITHUB_ENV
          fi

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION }}
          name: Release ${{ env.VERSION }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
